name: 'Auto Assign'
on: 
  pull_request:
    types: [opened, ready_for_review, reopened]
    
jobs:
  add-reviews:
    runs-on: ubuntu-latest
    steps:
#      - uses: kentaro-m/auto-assign-action@v1.2.4
#       with:
#          configuration-path: ".github/auto_assign_gremlins.yml"
      - name: Run assignment of reviewer team
        uses: nikosmoum/auto-assign-reviewer-team@v0.5
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          teamName: 'zy0112'
